# Generated by Django 2.0 on 2020-01-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.PositiveIntegerField(null=True)),
                ('shipmentDate', models.DateTimeField(auto_now_add=True)),
                ('orderItemId', models.PositiveIntegerField(null=True)),
                ('orderId', models.PositiveIntegerField(null=True)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('latestDeliveryDate', models.DateTimeField(auto_now_add=True)),
                ('ean', models.PositiveIntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('offerPrice', models.PositiveIntegerField(null=True)),
                ('offerCondition', models.CharField(blank=True, max_length=255)),
                ('fulfilmentMethod', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
