# Generated by Django 2.0 on 2020-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='ean',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='orderId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='orderItemId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
